Repository ricardoboss/Prolangle, pull requests merged in 2024-01, with the labels that each got.

#53 Added Dockerfile
  .dockerignore
  Dockerfile
  Prolangle.sln
  docker-compose.yml
  nginx.conf
Labels: meta

#87 Added Scratch
  Prolangle/Languages/Framework/Paradigms.cs
  Prolangle/Languages/Framework/SyntaxStyle.cs
  Prolangle/Languages/Scratch.cs
Labels: language

#70 Add Snippets Game
  Prolangle.Tests/GlobalUsings.cs
  Prolangle.Tests/GuessGameTests.cs
  Prolangle.Tests/LanguageMetadataProviderTests.cs
  Prolangle.Tests/MetadatumComparisonServiceTests.cs
  Prolangle.Tests/Prolangle.Tests.csproj
  Prolangle.Tests/SnippetRevealerTests.cs
  Prolangle.sln
  Prolangle/Languages/AppleScript.cs
  Prolangle/Languages/Assembly.cs
  Prolangle/Languages/Basic.cs
  Prolangle/Languages/C.cs
  Prolangle/Languages/CSharp.cs
  Prolangle/Languages/Cpp.cs
  Prolangle/Languages/Css.cs
  Prolangle/Languages/Dart.cs
  Prolangle/Languages/Go.cs
  Prolangle/Languages/Html.cs
  Prolangle/Languages/Java.cs
  Prolangle/Languages/Javascript.cs
  Prolangle/Languages/Lua.cs
  Prolangle/Languages/ObjectiveC.cs
  Prolangle/Languages/Pascal.cs
  Prolangle/Languages/Perl.cs
  Prolangle/Languages/Php.cs
  Prolangle/Languages/PowerShell.cs
  Prolangle/Languages/Python.cs
  Prolangle/Languages/Ruby.cs
  Prolangle/Languages/Rust.cs
  Prolangle/Languages/Sql.cs
  Prolangle/Languages/Step.cs
  Prolangle/Languages/Swift.cs
  Prolangle/Languages/VisualBasicClassic.cs
  Prolangle/Languages/VisualBasicNet.cs
  Prolangle/Languages/Xml.cs
  Prolangle/Layout/MainLayout.razor
  Prolangle/Pages/Home.razor
  Prolangle/Pages/Snippets.razor
  Prolangle/Program.cs
  Prolangle/Services/GameSeeder.cs
  Prolangle/Services/GuessGame.cs
  Prolangle/Services/LanguageSnippetProvider.cs
  Prolangle/Services/LanguagesProvider.cs
  Prolangle/Services/SnippetRevealer.cs
  Prolangle/Snippets/AppleScript/SimpleAppleScriptSnippet.cs
  Prolangle/Snippets/Assembly/HelloAssemblySnippet.cs
  Prolangle/Snippets/CSharp/SimpleCSharpSnippet.cs
  Prolangle/Snippets/CSharp/TaskCSharpSnippet.cs
  Prolangle/Snippets/Css/SimpleCssSnippet.cs
  Prolangle/Snippets/Dart/UserOrderDartSnippet.cs
  Prolangle/Snippets/Html/SimpleHtmlSnippet.cs
  Prolangle/Snippets/ICodeSnippet.cs
  Prolangle/Snippets/Javascript/SimpleJavascriptSnippet.cs
  Prolangle/Snippets/Php/DivideByZeroPhpSnippet.cs
  Prolangle/Snippets/Php/SimplePhpSnippet.cs
  Prolangle/Snippets/Sql/SimpleSqlSnippet.cs
  Prolangle/Snippets/Step/SimpleStepSnippet.cs
  Prolangle/Snippets/Xml/SimpleXmlSnippet.cs
Labels: enhancement

#100 For #94: expand CONTRIBUTING with a code snippets section
  CONTRIBUTING.md
  Prolangle/Snippets/ICodeSnippet.cs
Labels: meta

#104 Fix comparison for Applications.None
  Prolangle.Tests/MetadatumComparisonServiceTests.cs
  Prolangle/Services/MetadatumComparisonService.cs
Labels: bug

#99 for #94: Share button for Code Snippets game
  Prolangle.Tests/GuessGameTests.cs
  Prolangle.Tests/SnippetRevealerTests.cs
  Prolangle/Components/NextGameTimer.razor
  Prolangle/Components/ShareCodeSnippetButton.razor
  Prolangle/Pages/Home.razor
  Prolangle/Pages/Snippets.razor
  Prolangle/Program.cs
  Prolangle/Prolangle.csproj
  Prolangle/Services/GameSeeder.cs
Labels: enhancement

#101 #92: add a second footnote that explains the colors
  Prolangle/Components/MatchDisplay.razor
  Prolangle/Pages/Home.razor
  Prolangle/wwwroot/css/app.css
Labels: enhancement

#108 Added description for mobile applications
  Prolangle/Languages/Framework/Applications.cs
Labels: fix

#109 Add more application descriptions
  Prolangle/Languages/Framework/Applications.cs
Labels: fix

#106 Add description for Assembly syntax style
  Prolangle/Languages/Framework/SyntaxStyle.cs
Labels: fix

#112 fix #111: Add "Known For Building" descriptions to explanations page
  Prolangle/Pages/Explanations.razor
Labels: enhancement

#67 Configure as PWA
  Prolangle/Prolangle.csproj
  Prolangle/wwwroot/icon-512.png
  Prolangle/wwwroot/index.html
  Prolangle/wwwroot/manifest.webmanifest
  Prolangle/wwwroot/service-worker.js
  Prolangle/wwwroot/service-worker.published.js
Labels: enhancement
